version: '2'
services:
  redis:
    image: redis:3.0-alpine
    command: redis-server
    volumes:
      - /var/lib/redis/data
    ports:
      - 6379:6379

  postgres:
    restart: always
    image: postgres:10
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=present_easy

  # One node elasticsearch cluster
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:6.3.2
  #   ports:
  #     - "5601:5601"
  # app:
  #   image: present_easy
  #   restart: always
  #   build: .
  #   volumes:
  #     - ./:/app
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=present_easy
  #     - HOST=postgres
  #     - PORT=5432
  #     - APP_SETTINGS=config.DevelopmentConfig
  #     - APP_PORT=3000
  #     - SECRET_KEY=secret
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - ES_HOST=elasticsearch
  #     - ES_PORT=9200
  #   ports:
  #     - 80:80
  #   entrypoint: ["python", "app.py"]
