"""empty message

Revision ID: 8c392a377632
Revises: b33e3d4e24d5
Create Date: 2020-01-27 00:06:34.070119

"""

# revision identifiers, used by Alembic.
revision = '8c392a377632'
down_revision = 'b33e3d4e24d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('images', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
